name: Build student version

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: docker://pandoc/core:2.9
        with:
          args: "README.md" -o "README.pdf"

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: "README.pdf"
