name: Build student version

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make build directory
        run: mkdir build

      - name: Copy requirements.txt
        run: cp requirements.txt build/requirements.txt

      - name: Process notebooks
        run: find -iname '*.ipynb' -printf '%P\n' | xargs -I {} python process.py "{}" "build/{}"

      - name: Convert README to PDF
        uses: docker://pandoc/latex:2.9
        with:
          entrypoint: /bin/sh
          args: >-  # allows you to break string into multiple lines
            -c "
            tlmgr update --self &&
            tlmgr install framed tcolorbox environ trimspaces listingsutf8 &&
            pandoc
            --pdf-engine=xelatex
            --highlight-style kate
            -N
            -V colorlinks -V urlcolor=NavyBlue
            -V geometry:'top=2cm, bottom=1.5cm, left=2cm, right=2cm'
            -H head.tex
            --output=build/README.pdf
            README.md"

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: project-files
          path: build
